name = "wasm-pack"
engineVersion = "v1.0.0-beta.3"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "distro"
source = "../distro"

[[dependencies]]
name = "github"
source = "../github"

[[dependencies]]
name = "rust"
source = "../rust"
