version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    exclude-paths:
      - .github/workflows/ci.yaml
      - .github/workflows/dispatch.yaml
