[modules.dang-sdk]
source = "github.com/dagger/dang-sdk@572b0c5dbbe8b6a28beef7535161217ebef5086c"

# Until dang-sdk supports dagger-module.toml
check.skip = ["generate-all"]

# [modules.go-sdk]
# source = "github.com/dagger/go-sdk"

# Marker filename that skips generate when found at or above a Go SDK module root.
# settings.skipGenerateFilename = ""

[modules.daggerverse]
source = "daggerverse"

[modules.daggerverse.settings]
daggerCommit = "86d1d2f5791bcf3213d56903cfa81a3ba0abe54a"
concurrency = 5
exclude = "crates,distro,php-ext-rs"

[modules.dangpkg]
source = "github.com/sagikazarmark/dangpkg"

[modules.labctl]
source = "labctl"
settings.sessionId = "cmd://yq .session_id ~/.iximiuz/labctl/config.yaml | tr -d '\n'"
settings.accessToken = "cmd://yq .access_token ~/.iximiuz/labctl/config.yaml | tr -d '\n'"

# [modules.cargo-lock-tests]
# source = "cargo-lock/tests"

# [modules.crates-tests]
# source = "crates/tests"

# [modules.crypto-tests]
# source = "crypto/tests"

# [modules.dioxus-tests]
# source = "dioxus/tests"

# [modules.distro-tests]
# source = "distro/tests"

# [modules.dagger-gha-tests]
# source = "dagger-gha/tests"

# [modules.gha-tests]
# source = "gha/tests"

# [modules.github-tests]
# source = "github/tests"

# [modules.k3s-tests]
# source = "k3s/tests"

# [modules.kubectl-tests]
# source = "kubectl/tests"

# [modules.minisign-tests]
# source = "minisign/tests"

# [modules.olareg-tests]
# source = "olareg/tests"

# [modules.overlays-tests]
# source = "overlays/tests"

# [modules.php-dist-tests]
# source = "php-dist/tests"

# [modules.php-ext-rs-tests]
# source = "php-ext-rs/tests"

# [modules.registry-config-tests]
# source = "registry-config/tests"

# [modules.restate-tests]
# source = "restate/tests"

# [modules.rust]
# source = "rust"

# [modules.rust-tests]
# source = "rust/tests"

# [modules.wasm-pack]
# source = "wasm-pack"

# [modules.wrangler-tests]
# source = "wrangler/tests"

# [modules.zig-environment-tests]
# source = "zig-environment/tests"
