[modules.dang-sdk]
source = "github.com/dagger/dang-sdk@572b0c5dbbe8b6a28beef7535161217ebef5086c"

# Until dang-sdk supports dagger-module.toml
check.skip = ["generate-all"]

[modules.x509-tests]
source = "x509/tests"

[modules.crypto-tests]
source = "crypto/tests"

[modules.crates-tests]
source = "crates/tests"

[modules.distro-tests]
source = "distro/tests"

[modules.github-tests]
source = "github/tests"

[modules.kubectl-tests]
source = "kubectl/tests"

[modules.minisign-tests]
source = "minisign/tests"

[modules.olareg-tests]
source = "olareg/tests"

[modules.registry-config-tests]
source = "registry-config/tests"

[modules.rust-tests]
source = "rust/tests"

[modules.wrangler-tests]
source = "wrangler/tests"
