name = "rust-cross"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "github"
source = "../github"

[[dependencies]]
name = "rust-environment"
source = "../rust-environment"

[[dependencies]]
name = "build-environment"
source = "../build-environment"

[[dependencies]]
name = "overlays"
source = "../overlays"

[[dependencies]]
name = "zig-environment"
source = "../zig-environment"

[[dependencies]]
name = "macos-sdk"
source = "../macos-sdk"
