name = "kube-api-server"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "kubectl"
source = "../kubectl"

[[dependencies]]
name = "crypto"
source = "../crypto"
