name = "worker-build"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "rust-environment"
source = "../rust-environment"

[[dependencies]]
name = "cargo-lock"
source = "../cargo-lock"

[[dependencies]]
name = "overlays"
source = "../overlays"

[[dependencies]]
name = "wasm-tools"
source = "../wasm-tools"
