name = "php-ext-rs"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "rust-cross"
source = "../rust-cross"

[[dependencies]]
name = "php-dist"
source = "../php-dist"

[[dependencies]]
name = "zig-environment"
source = "../zig-environment"

[[dependencies]]
name = "macos-sdk"
source = "../macos-sdk"

[[dependencies]]
name = "overlays"
source = "../overlays"
