name = "zig-environment"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!tests"]

[[dependencies]]
name = "minisign"
source = "../minisign"

[[dependencies]]
name = "overlays"
source = "../overlays"
