name: Dagger
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
env:
  DAGGER_VERSION: v1.0.0-beta.3
jobs:
  check:
    name: ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: ["crates-tests:get", "distro-tests:kind:alpine", "distro-tests:kind:debian", "distro-tests:packages:alpine", "distro-tests:packages:debian", "github-tests:releases:get-defaults", "github-tests:releases:latest", "github-tests:resolve-repo:call-override", "github-tests:resolve-repo:default", "github-tests:resolve-repo:level-override", "minisign-tests:latest", "minisign-tests:public-key-file", "minisign-tests:public-key-string", "minisign-tests:version", "rust-tests:build", "rust-tests:clippy", "rust-tests:test", "wrangler-tests:container"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          verb: check
          args: ${{ matrix.check }}
          version: ${{ env.DAGGER_VERSION }}
