name: Dang

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: read

env:
  DAGGER_VERSION: 86d1d2f5791bcf3213d56903cfa81a3ba0abe54a

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run pipeline
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          verb: call
          module: .dagger/modules/dang-image
          args: publish --registry "ghcr.io" --repository "${{ github.repository_owner }}/dang:latest" --username ${{ github.actor }} --password env://GITHUB_TOKEN
          commit: ${{ env.DAGGER_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
